### ISSUE TITLE
panic: IO error: While fsync: a directory: Invalid argument

### ISSUE THREAD

**Issue by funlake** [lni/dragonboat-example#5]
Try the hello world demo got error information below
```
[root@localhost dragonboat-example]# CGO_LDFLAGS="-L/usr/local/lib -lrocksdb"  go build -v -o example-helloworld github.com/lni/dragonboat-example/helloworld
[root@localhost dragonboat-example]# ./example-helloworld -nodeid 1
node address: localhost:63001
2019-01-18 08:56:15.525426 I | dragonboat: go version: go1.11
2019-01-18 08:56:15.526223 I | dragonboat: dragonboat version: 2.0.0, raftlog type: three-stage, logdb type: fully-batched rocksdb
2019-01-18 08:56:15.526235 I | dragonboat: raft entry encoding scheme: colfer
2019-01-18 08:56:15.530460 I | dragonboat: no master server specified, running in standalone mode
2019-01-18 08:56:15.530540 W | dragonboat: DeploymentID not set in NodeHostConfig
2019-01-18 08:56:15.530553 I | dragonboat: DeploymentID set to 1
2019-01-18 08:56:15.535114 I | logdb: RangeDelete is disabled in ShardedRDB
2019-01-18 08:56:15.538846 E | logdb: direct io failed: open example-data/helloworld-data/node1/localhost.localdomain/00000000000000000001/logdb-0/.direct_io_test_safe_to_delete.dragonboat: invalid argument
2019-01-18 08:56:15.541918 E | logdb: direct io failed: open example-data/helloworld-data/node1/localhost.localdomain/00000000000000000001/logdb-0/.direct_io_test_safe_to_delete.dragonboat: invalid argument
panic: IO error: While fsync: a directory: Invalid argument

goroutine 1 [running]:
github.com/lni/dragonboat.(*NodeHost).createLogDB(0xc000120000, 0x0, 0xc000018330, 0x22, 0xc000018330, 0x22, 0xc8, 0x8bfba3, 0xf, 0x0, ...)
	/home/wwwroot/goroot/src/github.com/lni/dragonboat/nodehost.go:1112 +0x284
github.com/lni/dragonboat.NewNodeHostWithMasterClientFactory(0x0, 0xc000018330, 0x22, 0xc000018330, 0x22, 0xc8, 0x8bfba3, 0xf, 0x0, 0x0, ...)
	/home/wwwroot/goroot/src/github.com/lni/dragonboat/nodehost.go:225 +0xc78
github.com/lni/dragonboat.NewNodeHost(0x0, 0xc000018330, 0x22, 0xc000018330, 0x22, 0xc8, 0x8bfba3, 0xf, 0x0, 0x0, ...)
	/home/wwwroot/goroot/src/github.com/lni/dragonboat/nodehost.go:182 +0x5a
main.main()
	/home/wwwroot/goroot/src/github.com/lni/dragonboat-example/helloworld/main.go:185 +0x56c
```

**Comment by funlake** [comment]
Tried to traced error info and found error dumped at  line 63 of file ``` interal/logdb/sharded_rdb.go```
```
		db, err := openRDB(dir, lldir)
		if err != nil {
			return nil, err
		}
```
Was that because my rocksdb just not worked correctly?

**Comment by funlake** [comment]
But I found some log stuff just already created there inside the data dir of rocksdb
```
[root@localhost logdb-0]# pwd
/home/wwwroot/goroot/src/github.com/lni/dragonboat-example/example-data/helloworld-data/node1/localhost.localdomain/00000000000000000001/logdb-0
[root@localhost logdb-0]# ls
000039.log  IDENTITY  LOG                       LOG.old.1547799687068961  LOG.old.1547801126885749  LOG.old.1547801246427318  LOG.old.1547801311342172  LOG.old.1547801450808314  LOG.old.1547801775544894
CURRENT     LOCK      LOG.old.1547799547331081  LOG.old.1547800976670294  LOG.old.1547801134479345  LOG.old.1547801271807703  LOG.old.1547801342802272  LOG.old.1547801538449939  MANIFEST-000038
```

**Comment by lni** [comment]
fsync had an IO error. more specifically, it seems to me that fsync failed when rocksdb is trying to create its DB data directory. 

could you please check what is the filesystem type for /home/wwwroot/goroot/src/github.com/lni/dragonboat-example/example-data ?

**Comment by lni** [comment]
had a quick search online, it seems that there are similar reported rocksdb errors when storing rocksdb data into docker container with shared directories mounted from windows. any chance you are using docker linux container on windows? or some other similar complicated setup? 

running dragonboat in docker is 100% fine, we also have docker based nightly tests. but setups like linux docker container on windows is never tested.

**Comment by funlake** [comment]
Yeah, i mounted the $GOPATH dir from windows to linux with vagrant
I modified codes in ```example-helloworld/helloworld/main.go```,change path of  ```datadir``` to linux local directory ,everything just works like a charm.
Thanks again

**Comment by lni** [comment]
Cool. linux docker container running on a linux host should also work fine.
